DROP SCHEMA public CASCADE;
CREATE SCHEMA public;

/*
 *   TABLES
*/
CREATE TABLE public.users
(
    id       INTEGER                NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    email    CHARACTER VARYING(320) NOT NULL,
    password CHARACTER VARYING(25)  NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id),
    CONSTRAINT uc_users_email UNIQUE (email)
);

CREATE TABLE public.jobseekers
(
    id              INTEGER               NOT NULL,
    user_id INTEGER  NOT NULL,
    first_name      CHARACTER VARYING(35) NOT NULL,
    last_name       CHARACTER VARYING(35) NOT NULL,
    identity_number CHARACTER VARYING(11) NOT NULL,
    birth_date      DATE                  NOT NULL,
    CONSTRAINT pk_jobseekers PRIMARY KEY (id),
    CONSTRAINT fk_jobseekers_users FOREIGN KEY (user_id) REFERENCES public.users (id) ON DELETE CASCADE,
    CONSTRAINT uc_jobseekers_identity_number UNIQUE (identity_number)
);

CREATE TABLE public.employers
(
    id           INTEGER                NOT NULL,
    user_id INTEGER  NOT NULL,
    company_name CHARACTER VARYING(255) NOT NULL,
    website      CHARACTER VARYING(255) NOT NULL,
    phone_number CHARACTER VARYING(12)  NOT NULL,
    CONSTRAINT pk_employers PRIMARY KEY (id),
    CONSTRAINT fk_employers_users FOREIGN KEY (user_id) REFERENCES public.users (id) ON DELETE CASCADE
);

CREATE TABLE public.system_personels
(
    id       INTEGER               NOT NULL,
    user_id INTEGER  NOT NULL,
    username CHARACTER VARYING(35) NOT NULL,
    CONSTRAINT pk_system_personels PRIMARY KEY (id),
    CONSTRAINT fk_system_personels_users FOREIGN KEY (user_id) REFERENCES public.users (id) ON DELETE CASCADE
);

CREATE TABLE public.job_positions
(
    id        integer               NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 999999 CACHE 1 ),
    job_title character varying(50) NOT NULL,
    CONSTRAINT pk_job_positions PRIMARY KEY (id),
    CONSTRAINT uc_job_positions_job_title UNIQUE (job_title)
);

CREATE TABLE public.employers_activations
(
    id                    integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 999999 CACHE 1 ),
    employer_id           INTEGER NOT NULL,
    is_email_confirmed    boolean NOT NULL,
    is_employer_activated boolean NOT NULL,

    CONSTRAINT pk_employers_activations PRIMARY KEY (id),
    CONSTRAINT fk_employers_activations_employers FOREIGN KEY (employer_id) REFERENCES public.employers (id) ON DELETE CASCADE
);

CREATE TABLE public.jobseekers_activations
(
    id                 INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 999999 CACHE 1 ),
    jobseeker_id       INTEGER NOT NULL,
    is_email_confirmed boolean NOT NULL,
    is_mernis_valid    boolean NOT NULL,
    CONSTRAINT pk_jobseekers_activations PRIMARY KEY (id),
    CONSTRAINT fk_jobseekers_activations_jobseekers FOREIGN KEY (jobseeker_id) REFERENCES public.jobseekers (id) ON DELETE CASCADE
);
